version: "3.9"

services:
  spring-minio-template:
    image: yuihmoo/spring-minio-template
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VERSION=0.0.1
    volumes:
      - .:/application
    working_dir: /application
    command: |
      sh -c "
        chmod +x ./gradlew;
        ./gradlew --stop;
        ./gradlew build --continuous --quiet &
          ./gradlew bootRun;
      "

  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=ZGRyb290MTIhIQ==
      - MINIO_NOTIFY_WEBHOOK_ENABLE=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://host.docker.internal:8080/bucket/notifya
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data_minio:/data

volumes:
  db_data:
  data_minio: